# Generated by Django 6.0.3 on 2026-05-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
